name: My Brand Backend Continous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Dependencies installation
      run: npm install

    - name: Running Tests
      run: npm run test
# Putting on some environment variables
      env:
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
        PORT: ${{ secrets.PORT }}

# A job to deploy to render with auto deploy set to no on render
  deploy:
    name: Deploying
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
